### ISSUE TITLE
repackaged jakarta.* packages conflict with upstream ones

### ISSUE THREAD

**Issue by morgwai** [GedMarc/GuicedEE-Services#17]
guice package depends on repackaged versions of `jakarta.activation`, `jakarta.validation-api` and `jakarta.annotation-api` which conflict with upstream versions: for example when using upstream hibernate that depends on upstream `jakarta,activation`.
Not sure what the reason for repackaging these artifacts was, but surely it causes a lot of problems :(

**Comment by GedMarc** [comment]
The reasoning behind this is mostly to enable hibernate to be packaged into jlink native artifacts, which we use for all our deploys,

I will be making the dependencies optional as much as possible to not conflict with existing frameworks,
However you will lose the full modular implementation, and will only be able to use the automated module names from the desired libraries, and not be able to bundle a JRE for deployments

I see as well quite a few out of date deploys on maven, my apologies wasn't watching the automated builds as closely as I should have.

The upload this evening will be marked as version 2

**Comment by GedMarc** [comment]
Struggling on the renew of the TeamCity open source license

**Comment by GedMarc** [comment]
Only JACC is not modularized, all references have been updated
